### ISSUE TITLE
PDF multiple message export fails

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [thundernest/import-export-tools-ng#369]
Thunderbird Version: 102.6.0
NG Import Export Version: 12.0.2

_**Step to reproduce:**_

**offline:** 

Copy more than mails in local folder and export entire folder as pdf.

**alaternative online**:

Export more then 130 Mails from inbox as pdf

**alternative online**:

highlight more than 130 e-mails and export as pdf

**_what should happen:_**

All E-mail should be exported.

**_What acutally happens:_**

After exporting the first 130 e-mails the export will stop without any warning,...

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Thanks for the post, sorry for the issues...
It's certainly not impossible as users have been using this feature for quite some time. Of course with constant updates to TB stuff can always possibly break.
On my Windows 10 dev system, TB 102.6, IETNG 12.0.2, I ran several exports of 244 messages and one with 361 messages today. All completed without issue.

It seems some debugging is in order.
What OS are you on?
Have you exported more  than 130 pdfs in the past?
Anything further about your system of note?
Have you tried disabling all other addons?
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
OS: Windows 10 64 BIT
12 GB RAM
8 CORES
HDD (No SSD)

All my E-Mails are from a imap server.
I have no other add-ons in place.

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Have you checked the console output for any errors?
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
yes, see below:

Exception { name: "NS_ERROR_FAILURE", message: "Component returned 
failure code: 0x80004005 (NS_ERROR_FAILURE) 
[nsIEditor.getInlineSpellChecker]", result: 2147500037, filename: 
"chrome://messenger/content/messengercompose/MsgComposeCommands.js", 
lineNumber: 6997, columnNumber: 0, data: null, stack: 
"ComposeChangeLanguage@chrome://messenger/content/messengercompose/MsgComposeCommands.js:6997:13\n", 
location: XPCWrappedNative_NoHelper }



Uncaught (in promise)
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, 
filename: "", lineNumber: 0, columnNumber: 0, data: null, stack: "", 
location: null }

columnNumber: 0

data: null

filename: ""

lineNumber: 0

location: null

message: ""

name: "NS_ERROR_FAILURE"

result: 2147500037

stack: ""

<prototype>: ExceptionPrototype { toString: toString(), name: Getter, 
message: Getter, … }

columnNumber:

data:

filename:

lineNumber:

location:

message:

name:

result:

stack:

toString: function toString()

Symbol(Symbol.toStringTag): "Exception"

<get columnNumber()>: function columnNumber()

<get data()>: function data()

<get filename()>: function filename()

<get lineNumber()>: function lineNumber()

<get location()>: function location()

<get message()>: function message()

<get name()>: function name()

<get result()>: function result()

<get stack()>: function stack()

<set stack()>: function stack()

<prototype>: Object { … }

**Comment by MrLoverLoverMMMM** [comment]
my e-mails are with  german Umlaufe, maybe thats an issue?

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Hmmm, all those errors are something else, not clear what, but it looks like errors during a message composition.
For subsequent console captures I suggest clear log, perform test then capture log.

The question about the German characters is that they are not an issue.
Is it possible you were always trying to export the same set of emails? If so we may just have a problematic email
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
Well, this error happens exactly when the export stops.
At the exact 130 mail.
I tried it with different sets of e-mails.
Maybe some attachments or ics or somthing could make any issues?
I actually really did it that way that I start the export and exactly when it stops i get:

ncaught (in promise)
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037,
filename: "", lineNumber: 0, columnNumber: 0, data: null, stack: "",
location: null }

columnNumber: 0

data: null

filename: ""

lineNumber: 0

location: null

message: ""

name: "NS_ERROR_FAILURE"

result: 2147500037

stack: ""

: ExceptionPrototype { toString: toString(), name: Getter,
message: Getter, … }

columnNumber:

data:

filename:

lineNumber:

location:

message:

name:

result:

stack:

toString: function toString()

Symbol(Symbol.toStringTag): "Exception"

<get columnNumber()>: function columnNumber()

<get data()>: function data()

<get filename()>: function filename()

<get lineNumber()>: function lineNumber()

<get location()>: function location()

<get message()>: function message()

<get name()>: function name()

<get result()>: function result()

<get stack()>: function stack()

<set stack()>: function stack()

: Object { … }

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Since I don't see any relevant errors that I can tell I think I may have to add some debug that might help us.
@cleidigh

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
I assume this is still live?
Are you still interested if I add debug to work on this?
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
yes the issue is still persissting.
it would be very nice if there would be a solution for this issue.

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Ok I will work on some pdf debug to add to my next beta.
Also I forgot to ask if this is something you did in the past successfully?
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
Yes, non pdf export is and was always working

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Ok so I made a beta with message level debug to see if we can learn more.
After installing do the following : 
- Have two folders with different messages > 130
- for each folder clear log
- run export 
- right click, select all, copy to text file 
- post text files 

https://github.com/thundernest/import-export-tools-ng/blob/v12.0.3/xpi/import-export-tools-ng-12.0.3-b5-tb.xpi
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
Here the error-logs of both tries on 2 different folders as soon as the export starts to fail / stopps itself. Both folders are local at already downloaded a thunderbird. Private information is marked as _BLACKEDOUT_:



### 1 (error at message > 130):

...
IETNG: End:  127 127_Re_Anfrage_Rackschienen_20210203_sender_Sebastian_Stoebich___it-TREND_recipient_BLACKEDOUT_BLACKEDOUT.pdf 
Date Tue Jan 17 2023 06:54:08 GMT+0100 (GMT+01:00)
mboximport.js:281:12
IETNG: Start:  128 128_Re_Anfrage_Rackschienen_20210203_sender_Sebastian_Stoebich___it-TREND_recipient_BLACKEDOUT_BLACKEDOUT.pdf 
Date Tue Jan 17 2023 06:54:08 GMT+0100 (GMT+01:00)
mboximport.js:278:12
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". {eee2e4d4-701b-49ec-82b3-5be18d349a1a}
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". blank
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". Offline Files
IETNG: End:  128 128_Re_Anfrage_Rackschienen_20210203_sender_Sebastian_Stoebich___it-TREND_recipient_BLACKEDOUT_BLACKEDOUT.pdf 
Date Tue Jan 17 2023 06:54:11 GMT+0100 (GMT+01:00)
mboximport.js:281:12
IETNG: Start:  129 129_Re_Anfrage_Rackschienen_20210203_sender_Sebastian_Stoebich___it-TREND_recipient__BLACKEDOUT_BLACKEDOUT_.pdf 
Date Tue Jan 17 2023 06:54:11 GMT+0100 (GMT+01:00)
mboximport.js:278:12
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". {10d5e083-d501-47f9-9098-6a4cd020f8b4}
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". blank
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". Offline Files
IETNG: End:  129 129_Re_Anfrage_Rackschienen_20210203_sender_Sebastian_Stoebich___it-TREND_recipient__BLACKEDOUT_BLACKEDOUT_.pdf 
Date Tue Jan 17 2023 06:54:14 GMT+0100 (GMT+01:00)
mboximport.js:281:12
IETNG: Start:  130 130_Re_Anfrage_Rackschienen_20210203_sender_Sebastian_Stoebich___it-TREND_recipient__BLACKEDOUT_BLACKEDOUT_.pdf 
Date Tue Jan 17 2023 06:54:14 GMT+0100 (GMT+01:00)
mboximport.js:278:12
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". {ea1bd798-aa17-4e39-b0c0-90002e2ad060}
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". blank
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". Offline Files
IETNG: End:  130 130_Re_Anfrage_Rackschienen_20210203_sender_Sebastian_Stoebich___it-TREND_recipient__BLACKEDOUT_BLACKEDOUT_.pdf 
Date Tue Jan 17 2023 06:54:17 GMT+0100 (GMT+01:00)
mboximport.js:281:12
IETNG: Start:  131 131_Anfrage_von_Amazon-Kunde_BLACKEDOUT_BLACKEDOUT__Besch_digten_oder_defekten_Artikel_erhalten_Bestellung__303-2232404-1289133__20210203_sender_ProCook_Ltd_Germany_-_Amazon_Payments_recipient_BLACKEDOUT_BLACKEDOUT_mail_BLACKEDOUT_at.pdf 
Date Tue Jan 17 2023 06:54:17 GMT+0100 (GMT+01:00)
mboximport.js:278:12
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24
Diese Seite befindet sich im Fast-Standards-Modus ("almost standards mode"). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". {bb212a4d-307f-48fb-a3d6-ace58501805b}
Diese Seite befindet sich im Fast-Standards-Modus ("almost standards mode"). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". blank
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". Offline Files
TypeError: browser is null PrintingParent.jsm:14:7
    receiveMessage resource://gre/actors/PrintingParent.jsm:14
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24


Uncaught (in promise) 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "", lineNumber: 0, columnNumber: 0, data: null, stack: "", location: null }
​
columnNumber: 0
​
data: null
​
filename: ""
​
lineNumber: 0
​
location: null
​
message: ""
​
name: "NS_ERROR_FAILURE"
​
result: 2147500037
​
stack: ""
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
​​
columnNumber: 
​​
data: 
​​
filename: 
​​
lineNumber: 
​​
location: 
​​
message: 
​​
name: 
​​
result: 
​​
stack: 
​​
toString: function toString()
​​
Symbol(Symbol.toStringTag): "Exception"
​​
<get columnNumber()>: function columnNumber()
​​
<get data()>: function data()
​​
<get filename()>: function filename()
​​
<get lineNumber()>: function lineNumber()
​​
<get location()>: function location()
​​
<get message()>: function message()
​​
<get name()>: function name()
​​
<get result()>: function result()
​​
<get stack()>: function stack()
​​
<set stack()>: function stack()
​​
<prototype>: Object { … }



### 2 (error at message > 260):

...
IETNG: End:  255 255_Re__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__Nachricht__ber_https___www_ap-terrarienwaende_de_kontakt__20220219_sender_Alexander_Posch_recipient_BLACKEDOUT_BLACKEDOUT.pdf 
Date Tue Jan 17 2023 06:46:38 GMT+0100 (GMT+01:00)
mboximport.js:281:12
IETNG: Start:  256 256_Re__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__Nachricht__ber_https___www_ap-terrarienwaende_de_kontakt__20220219_sender_Alexander_Posch_recipient_BLACKEDOUT_BLACKEDOUT.pdf 
Date Tue Jan 17 2023 06:46:38 GMT+0100 (GMT+01:00)
mboximport.js:278:12
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". {7f86e31b-7db5-4351-a44d-acd47fbb921e}
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". blank
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". Posteingang
IETNG: End:  256 256_Re__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__Nachricht__ber_https___www_ap-terrarienwaende_de_kontakt__20220219_sender_Alexander_Posch_recipient_BLACKEDOUT_BLACKEDOUT.pdf 
Date Tue Jan 17 2023 06:46:40 GMT+0100 (GMT+01:00)
mboximport.js:281:12
IETNG: Start:  257 257_Re__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__RE__Aw__Nachricht__ber_https___www_ap-terrarienwaende_de_kontakt__20220219_sender_Alexander_Posch_recipient_BLACKEDOUT_BLACKEDOUT.pdf 
Date Tue Jan 17 2023 06:46:40 GMT+0100 (GMT+01:00)
mboximport.js:278:12
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". {b6f94cbe-fe81-4170-934a-f88cb9ae9dce}
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". blank
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". Posteingang
TypeError: browser is null PrintingParent.jsm:14:7
    receiveMessage resource://gre/actors/PrintingParent.jsm:14
TypeError: browser is null BrowserElementParent.jsm:24:21
    receiveMessage resource://gre/actors/BrowserElementParent.jsm:24
Uncaught (in promise) 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "", lineNumber: 0, columnNumber: 0, data: null, stack: "", location: null }
... (similar error as message 1)

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Can you please post these  as two text file attachments, I cannot read the paste very well.
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
of course, no problem ;)
[log folder 1.txt](https://github.com/thundernest/import-export-tools-ng/files/10442574/log.folder.1.txt)
[log folder 2.txt](https://github.com/thundernest/import-export-tools-ng/files/10442575/log.folder.2.txt)

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
That helped a lot. We discussed this in our developers meeting today and I will have some new test code shortly.
@cleidigh

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Allright I have b6 beta. It's more than just extra debug. It has an exception detection and a recovery that hopefully gets past the issue.
Capture the entire log this time to see all output.

https://github.com/thundernest/import-export-tools-ng/blob/v12.0.3/xpi/import-export-tools-ng-12.0.3-b6-tb.xpi
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
Now it was running without stopping, but it did not export all mails.
The logs are attached with privat info blackedout.
[1.txt](https://github.com/thundernest/import-export-to
[2.txt](https://github.com/thundernest/import-export-tools-ng/files/10507772/2.txt)
ols-ng/files/10507303/1.txt)

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
The result for t1 actually looks good. There were 16 error / recovery events. 1236 pdfs exported out of 1252.
There was a counter error advancing incorrectly so I think if I fix that you will get all1252.
the root cause seems to be an internal timing problem in thunderbird.
I will post a beta tomorrow.
@cleidigh

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
I believe I have fixed the recovery mechanism.
Two notes: 
- I cannot test the exception so hopefully no errors there 
- We may still find the messages fail for some reason and we will have to analyze them

My hope is it is just recovering from the timing issue.

https://github.com/thundernest/import-export-tools-ng/blob/v12.0.3/xpi/import-export-tools-ng-12.0.3-b7-tb.xpi
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
It still does not export all e-mails.
There is 1252 mails and it exported 1236.
logs are the same, thats why i did not attach them.

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Alright, learned more roughly comparing logs.
I appreciate your patience and willingness to do this testing. Unfortunately unless people just gave me their email (duh, not possible) this back and forth is necessary.

There are at least two issues, however, it is difficult to know yet if that is it.
Clearly there is the timing issue and these recover with the new delay/retry. The second issue which has no recovery is filenames that exceed 249 total characters. IETNG has an option to truncate filenames to 249 for Windows.
I think that option must be off as I see some filenames exceeding 249 before even adding the path which is included in the limit.

Some examples 


1106_Re__stefan-niedermann_nextcloud-deck__Instable_on_Samsung_Phones_with_connection_changes_from_wifi__celular_from_time_to_time__Issue__1169__20211130_sender_Niedermann_IT-Dienstleistungen_recipient_stefan-niedermann_nextcloud-deck.pdf
len 239

887_Re__nickv-nextcloud_twofactor_nextcloud_notification__Sinsce_Nextcloud_Version_21_0_5_it_does_not_authentificate_correctly_anymore___556__20211004_sender_Joas_Schilling_recipient_nickv-nextcloud_twofactor_nextcloud_notification.pdf
len 236


1107_Re__stefan-niedermann_nextcloud-deck__Instable_on_Samsung_Phones_with_connection_changes_from_wifi__celular_from_time_to_time__Issue__1169__20211130_sender_Artur_recipient_stefan-niedermann_nextcloud-deck.pdf
len 213

147_Re_Anfrage_von_Amazon-Kunde_BLACKEDOUT_BLACKEDOUT__Besch_digten_oder_defekten_Artikel_erhalten_Bestellung__303-2232404-1289133__20210205_sender_ProCook_Ltd_Germany_-_Amazon_Payments_recipient_BLACKEDOUT_BLACKEDOUT_mail_pgdatacenter_at.pdf
len 242

181_Re_Anfrage_von_Amazon-Kunde_BLACKEDOUT_BLACKEDOUT__Besch_digten_oder_defekten_Artikel_erhalten_Bestellung__303-2232404-1289133__20210212_sender_ProCook_Ltd_Germany_-_Amazon_Payments_recipient_BLACKEDOUT_BLACKEDOUT_mail_pgdatacenter_at.pdf
len 242

209_Re_Fragen_zu_meinem_Account____20210226_sender__Lisa_von_Grover__recipient_BLACKEDOUT_BLACKEDOUT_mail_pgdatacenter_at.pdf
len 126
success after 1 retry

400_Zahlungserinnerung_20210513_sender_Gebetsroither_International_recipient_BLACKEDOUT_BLACKEDOUT_mail_pgdatacenter_at.pdf
len 123
success after 1 retry

456_Re_Ford_Ranger_Raptor_20210601_sender__Autohaus_Danninger_-_Krizevac_Emir__recipient___BLACKEDOUT_BLACKEDOUT__.pdf
len 120
success after 1 retry 

628_Re_Rado_Uhren_20210719_sender__Juwelier_Mayrhofer__Verkauf_Hauptplatz__recipient__BLACKEDOUT_BLACKEDOUT_.pdf
len 112
success after 1 retry 

633_Re_Hello__Which_models_you_offer_are_automatic___Premetus_or_only_Preomoteus_Automatic__are_there_any_other_automatic_modells__Which_cases_of_those_modells_are_not_plated__are_full__best_regards_BLACKEDOUT_-__ZXD-NCXHM-086__20210719_sender__James_Reid__recipient__BLACKEDOUT_BLACKEDOUT_.pdf
len 294

888_Re_Versicherung_Abbuchung_20211004_sender_Rene_Kuhn_recipient_BLACKEDOUT_BLACKEDOUT.pdf
len 91
success after 1 retry 

1107_Re__stefan-niedermann_nextcloud-deck__Instable_on_Samsung_Phones_with_connection_changes_from_wifi__celular_from_time_to_time__Issue__1169__20211130_sender_Artur_recipient_stefan-niedermann_nextcloud-deck.pdf
len 214

So I can't reconcile the numbers exactly yet the failures from the last (partial) log are long filenames.
My hope is setting that cutoff gets the other messages to export.
Also do full logs so we can compare full runs.
@cleidigh

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Have you been able to shorten the names and see if everything exports?
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
The problem is, that I don't have a testset of e-mails for such an test.
Could you send me an archieve or something that I could test that?

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
If the same messages fail to write then I think we have to look at those specifically.
In other words its not the quantity of messages its particular messages.
If you enabled the name length cutoff you should see a difference in the log
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
OK
I did enable cutoff for subject as well as name.
Now it works without any issues.
The problem though is, that I would like to export the full name + subject, otherwise I would have activated the cutoff beforehand.
The logs are attached though.

**Comment by MrLoverLoverMMMM** [comment]
[logs.txt](https://github.com/thundernest/import-export-tools-ng/files/10740255/logs.txt)

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Ahh, finally!
Sorry that took so long.
The issue is windows setting this full path+name limit forever.
There is a method to extend this, see MS tech note: 
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

I have never used this myself. I would also warn that doing so would make the long filename files non-portable as practically no other systems would be configured this way.
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
Ok, thx

**Comment by cleidigh** [comment]
@MrLoverLoverMMMM 
Reviews are always welcome!
Shall we close?
@cleidigh

**Comment by MrLoverLoverMMMM** [comment]
Ok
