### ISSUE TITLE
Importing at the account level

### ISSUE THREAD

**Issue by gabraham44** [thundernest/import-export-tools-ng#456]
I've installed ver. 14 and find that the ability to import an mbox file is missing. Where can find an add-on to replace this function?

**Comment by cleidigh** [comment]
@gabraham44 
You can only import to a Local folder.
Create an imput folder under local folders 
then right click on that folder and you will see the Import mbox files menu option.
@cleidigh

**Comment by grainyms** [comment]
I'm not seeing Import mbox files menu option - even in Local Folder, w right click

**Comment by cleidigh** [comment]
@gabraham44 
Were you successful?
@cleidigh

**Comment by carmensmp** [comment]
Solved with latest update!

**Comment by JWaldenback** [comment]
I had the exact same problem, didn't realize that I had to create a new folder under local folders and right click on it to get the "Import mbox files" option to show. If one right clicks on the regular local folder accordion that option is not available, see here:

![image](https://github.com/thundernest/import-export-tools-ng/assets/19432538/97999d5d-65d8-4857-963a-17fbd85ae652)

**Comment by JWaldenback** [comment]
Looking at the different Youtube videos that go through how to import an mbox file they seem to be able to click on the regular local folders accordion and still get the import option to show. Could it be the case that something has changed in a recent update? 🙂

**Comment by JWaldenback** [comment]
@cleidigh I see. I guess there will be people who follow YouTube guides and other guides on how to import mbox files who will be confused. But on the other hand, new YouTube guides and text guides will eventually be created and then the problem is no more.

Check 1.20 into this video to see how all the video guides shown how to do it (until now):
https://youtu.be/zpX2X4wvAfA?feature=shared

**Comment by cleidigh** [comment]
@JWaldenback 
Will look into seeing about adding import at the account level.
@cleidigh

**Comment by cleidigh** [comment]
Added in b4
- #466 
@cleidigh
